-- Stockita | Aster Konveksi
-- Jalankan seluruh file ini pada Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku text NOT NULL UNIQUE,
  name text NOT NULL,
  category text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('material', 'finished')),
  unit text NOT NULL DEFAULT 'pcs',
  stock numeric(14, 2) NOT NULL DEFAULT 0 CHECK (stock >= 0),
  min_stock numeric(14, 2) NOT NULL DEFAULT 0 CHECK (min_stock >= 0),
  cost_price numeric(16, 2) NOT NULL DEFAULT 0 CHECK (cost_price >= 0),
  sale_price numeric(16, 2) NOT NULL DEFAULT 0 CHECK (sale_price >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice text NOT NULL UNIQUE,
  customer text NOT NULL,
  note text NOT NULL DEFAULT '',
  sold_at timestamptz NOT NULL DEFAULT now(),
  total numeric(16, 2) NOT NULL CHECK (total >= 0),
  cogs numeric(16, 2) NOT NULL CHECK (cogs >= 0)
);

CREATE TABLE IF NOT EXISTS public.sale_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id bigint NOT NULL REFERENCES public.sales(id),
  product_id bigint NOT NULL REFERENCES public.products(id),
  product_name text NOT NULL,
  quantity numeric(14, 2) NOT NULL CHECK (quantity > 0),
  unit_price numeric(16, 2) NOT NULL CHECK (unit_price >= 0),
  unit_cost numeric(16, 2) NOT NULL CHECK (unit_cost >= 0),
  subtotal numeric(16, 2) NOT NULL CHECK (subtotal >= 0),
  line_cogs numeric(16, 2) NOT NULL CHECK (line_cogs >= 0)
);

CREATE TABLE IF NOT EXISTS public.payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id bigint NOT NULL REFERENCES public.sales(id),
  amount numeric(16, 2) NOT NULL CHECK (amount > 0),
  method text NOT NULL DEFAULT 'Transfer',
  paid_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.stock_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id),
  movement_type text NOT NULL CHECK (movement_type IN ('initial', 'adjustment', 'sale')),
  quantity_delta numeric(14, 2) NOT NULL CHECK (quantity_delta <> 0),
  unit_cost numeric(16, 2) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
  note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sales_sold_at ON public.sales (sold_at DESC);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale_id ON public.sale_items (sale_id);
CREATE INDEX IF NOT EXISTS idx_payments_sale_id ON public.payments (sale_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_product_id ON public.stock_movements (product_id, created_at DESC);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.products, public.sales, public.sale_items, public.payments, public.stock_movements TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

INSERT INTO public.products (id, sku, name, category, kind, unit, stock, min_stock, cost_price, sale_price, created_at) VALUES
  (1, 'MAT-001', 'Kaos polos cotton combed 24s', 'Kaos', 'material', 'pcs', 58, 20, 28000, 0, '2026-09-27T14:13:43.281Z'),
  (2, 'MAT-002', 'Tote bag kanvas polos', 'Tas', 'material', 'pcs', 32, 10, 12500, 0, '2026-09-27T14:13:43.281Z'),
  (3, 'MAT-003', 'Akrilik bening 4 x 4 cm', 'Akrilik', 'material', 'lembar', 145, 40, 2500, 0, '2026-09-27T14:13:43.281Z'),
  (4, 'MAT-004', 'Kertas transfer DTF', 'Sablon', 'material', 'meter', 18, 5, 55000, 0, '2026-09-27T14:13:43.281Z'),
  (5, 'FIN-001', 'Kaos sablon custom Aster', 'Kaos', 'finished', 'pcs', 16, 5, 55000, 95000, '2026-09-27T14:13:43.281Z'),
  (6, 'FIN-002', 'Tote bag sablon custom', 'Tas', 'finished', 'pcs', 10, 4, 27000, 55000, '2026-09-27T14:13:43.281Z'),
  (7, 'FIN-003', 'Gantungan kunci akrilik custom', 'Aksesori', 'finished', 'pcs', 24, 8, 8000, 18000, '2026-09-27T14:13:43.281Z'),
  (8, 'FIN-004', 'Hoodie bordir custom', 'Pakaian', 'finished', 'pcs', 6, 3, 130000, 220000, '2026-09-27T14:13:43.281Z'),
  (9, 'AST-9991251', 'PDH Ormawa', 'PDH', 'finished', 'pcs', 0, 0, 100000, 120000, '2026-09-27T14:39:51.257Z')
ON CONFLICT (sku) DO NOTHING;

INSERT INTO public.sales (id, invoice, customer, note, sold_at, total, cogs) VALUES
  (1, 'AST-20260927-21607', 'Rinjani', 'PDH Ormawa', '2026-09-27T14:42:01.606Z', 10800000, 9000000)
ON CONFLICT (invoice) DO NOTHING;

INSERT INTO public.sale_items (id, sale_id, product_id, product_name, quantity, unit_price, unit_cost, subtotal, line_cogs) VALUES
  (1, 1, 9, 'PDH Ormawa', 90, 120000, 100000, 10800000, 9000000)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.payments (id, sale_id, amount, method, paid_at) VALUES
  (1, 1, 6000000, 'QRIS', '2026-09-27T14:42:01.606Z')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.stock_movements (id, product_id, movement_type, quantity_delta, unit_cost, note, created_at) VALUES
  (1, 1, 'initial', 58, 28000, 'Saldo awal', '2026-09-27T14:13:43.281Z'),
  (2, 2, 'initial', 32, 12500, 'Saldo awal', '2026-09-27T14:13:43.281Z'),
  (3, 3, 'initial', 145, 2500, 'Saldo awal', '2026-09-27T14:13:43.281Z'),
  (4, 4, 'initial', 18, 55000, 'Saldo awal', '2026-09-27T14:13:43.281Z'),
  (5, 5, 'initial', 16, 55000, 'Saldo awal', '2026-09-27T14:13:43.281Z'),
  (6, 6, 'initial', 10, 27000, 'Saldo awal', '2026-09-27T14:13:43.281Z'),
  (7, 7, 'initial', 24, 8000, 'Saldo awal', '2026-09-27T14:13:43.281Z'),
  (8, 8, 'initial', 6, 130000, 'Saldo awal', '2026-09-27T14:13:43.281Z'),
  (9, 9, 'initial', 90, 100000, 'Saldo awal', '2026-09-27T14:39:51.257Z'),
  (10, 9, 'sale', -90, 100000, 'Penjualan AST-20260927-21607', '2026-09-27T14:42:01.606Z')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.products', 'id'), COALESCE((SELECT max(id) FROM public.products), 1));
SELECT setval(pg_get_serial_sequence('public.sales', 'id'), COALESCE((SELECT max(id) FROM public.sales), 1));
SELECT setval(pg_get_serial_sequence('public.sale_items', 'id'), COALESCE((SELECT max(id) FROM public.sale_items), 1));
SELECT setval(pg_get_serial_sequence('public.payments', 'id'), COALESCE((SELECT max(id) FROM public.payments), 1));
SELECT setval(pg_get_serial_sequence('public.stock_movements', 'id'), COALESCE((SELECT max(id) FROM public.stock_movements), 1));

CREATE OR REPLACE FUNCTION public.stockita_create_product(p_product jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_product public.products%ROWTYPE;
BEGIN
  INSERT INTO public.products (sku, name, category, kind, unit, stock, min_stock, cost_price, sale_price)
  VALUES (
    COALESCE(NULLIF(p_product->>'sku', ''), 'AST-' || right(extract(epoch FROM clock_timestamp())::bigint::text, 7)),
    btrim(p_product->>'name'), COALESCE(NULLIF(btrim(p_product->>'category'), ''), 'Lainnya'),
    p_product->>'kind', COALESCE(NULLIF(btrim(p_product->>'unit'), ''), 'pcs'),
    COALESCE((p_product->>'stock')::numeric, 0), COALESCE((p_product->>'min_stock')::numeric, 0),
    COALESCE((p_product->>'cost_price')::numeric, 0), COALESCE((p_product->>'sale_price')::numeric, 0)
  ) RETURNING * INTO v_product;
  IF v_product.stock > 0 THEN
    INSERT INTO public.stock_movements (product_id, movement_type, quantity_delta, unit_cost, note)
    VALUES (v_product.id, 'initial', v_product.stock, v_product.cost_price, 'Saldo awal');
  END IF;
  RETURN to_jsonb(v_product);
END;
$$;

CREATE OR REPLACE FUNCTION public.stockita_adjust_stock(p_product_id bigint, p_quantity_delta numeric, p_note text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_product public.products%ROWTYPE;
BEGIN
  IF p_quantity_delta = 0 THEN RAISE EXCEPTION 'Jumlah perubahan stok harus bukan nol.'; END IF;
  UPDATE public.products SET stock = stock + p_quantity_delta
  WHERE id = p_product_id AND stock + p_quantity_delta >= 0
  RETURNING * INTO v_product;
  IF NOT FOUND THEN RAISE EXCEPTION 'Barang tidak ditemukan atau stok tidak mencukupi.'; END IF;
  INSERT INTO public.stock_movements (product_id, movement_type, quantity_delta, unit_cost, note)
  VALUES (v_product.id, 'adjustment', p_quantity_delta, v_product.cost_price, COALESCE(NULLIF(btrim(p_note), ''), 'Penyesuaian stok'));
  RETURN to_jsonb(v_product);
END;
$$;

CREATE OR REPLACE FUNCTION public.stockita_create_sale(p_customer text, p_note text, p_items jsonb, p_initial_payment numeric, p_payment_method text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_sale_id bigint;
  v_invoice text;
  v_now timestamptz := now();
  v_total numeric(16, 2) := 0;
  v_cogs numeric(16, 2) := 0;
  v_item record;
  v_product public.products%ROWTYPE;
  v_sale public.sales%ROWTYPE;
BEGIN
  IF NULLIF(btrim(p_customer), '') IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'Nama pelanggan dan minimal satu barang wajib diisi.';
  END IF;
  FOR v_item IN
    SELECT product_id, sum(quantity) AS quantity
    FROM jsonb_to_recordset(p_items) AS x(product_id bigint, quantity numeric, unit_price numeric)
    GROUP BY product_id
  LOOP
    SELECT * INTO v_product FROM public.products WHERE id = v_item.product_id FOR UPDATE;
    IF NOT FOUND OR v_product.stock < v_item.quantity THEN
      RAISE EXCEPTION 'Stok barang tidak mencukupi.';
    END IF;
  END LOOP;
  SELECT sum(x.quantity * x.unit_price), sum(x.quantity * p.cost_price)
  INTO v_total, v_cogs
  FROM jsonb_to_recordset(p_items) AS x(product_id bigint, quantity numeric, unit_price numeric)
  JOIN public.products p ON p.id = x.product_id;
  IF p_initial_payment < 0 OR p_initial_payment > v_total THEN
    RAISE EXCEPTION 'Nominal pembayaran awal tidak valid.';
  END IF;
  v_sale_id := nextval(pg_get_serial_sequence('public.sales', 'id'));
  v_invoice := 'AST-' || to_char(v_now, 'YYYYMMDD') || '-' || lpad(v_sale_id::text, 5, '0');
  INSERT INTO public.sales (id, invoice, customer, note, sold_at, total, cogs)
  VALUES (v_sale_id, v_invoice, btrim(p_customer), COALESCE(p_note, ''), v_now, v_total, v_cogs)
  RETURNING * INTO v_sale;
  FOR v_item IN
    SELECT x.product_id, x.quantity, x.unit_price, p.name, p.cost_price
    FROM jsonb_to_recordset(p_items) AS x(product_id bigint, quantity numeric, unit_price numeric)
    JOIN public.products p ON p.id = x.product_id
  LOOP
    INSERT INTO public.sale_items (sale_id, product_id, product_name, quantity, unit_price, unit_cost, subtotal, line_cogs)
    VALUES (v_sale_id, v_item.product_id, v_item.name, v_item.quantity, v_item.unit_price, v_item.cost_price,
      v_item.quantity * v_item.unit_price, v_item.quantity * v_item.cost_price);
    UPDATE public.products SET stock = stock - v_item.quantity WHERE id = v_item.product_id;
    INSERT INTO public.stock_movements (product_id, movement_type, quantity_delta, unit_cost, note, created_at)
    VALUES (v_item.product_id, 'sale', -v_item.quantity, v_item.cost_price, 'Penjualan ' || v_invoice, v_now);
  END LOOP;
  IF p_initial_payment > 0 THEN
    INSERT INTO public.payments (sale_id, amount, method, paid_at)
    VALUES (v_sale_id, p_initial_payment, COALESCE(NULLIF(p_payment_method, ''), 'Transfer'), v_now);
  END IF;
  RETURN to_jsonb(v_sale);
END;
$$;

CREATE OR REPLACE FUNCTION public.stockita_add_payment(p_sale_id bigint, p_amount numeric, p_method text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_sale public.sales%ROWTYPE;
  v_paid numeric(16, 2);
BEGIN
  SELECT * INTO v_sale FROM public.sales WHERE id = p_sale_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Transaksi tidak ditemukan.'; END IF;
  SELECT COALESCE(sum(amount), 0) INTO v_paid FROM public.payments WHERE sale_id = p_sale_id;
  IF p_amount <= 0 OR p_amount > v_sale.total - v_paid THEN
    RAISE EXCEPTION 'Nominal pembayaran melebihi sisa tagihan atau tidak valid.';
  END IF;
  INSERT INTO public.payments (sale_id, amount, method) VALUES (p_sale_id, p_amount, COALESCE(NULLIF(p_method, ''), 'Transfer'));
  RETURN jsonb_build_object('ok', true, 'remaining', v_sale.total - v_paid - p_amount);
END;
$$;

REVOKE ALL ON FUNCTION public.stockita_create_product(jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.stockita_adjust_stock(bigint, numeric, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.stockita_create_sale(text, text, jsonb, numeric, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.stockita_add_payment(bigint, numeric, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.stockita_create_product(jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.stockita_adjust_stock(bigint, numeric, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.stockita_create_sale(text, text, jsonb, numeric, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.stockita_add_payment(bigint, numeric, text) TO service_role;
